### ISSUE TITLE
Cannot deploy example

### ISSUE THREAD

**Issue by zklim** [OffchainLabs/stylus-sdk-c#10]
Got the below error message:
```
Reading WASM file at siphash.wasm
Uncompressed WASM size: 1.4 KB
Compressed WASM size to be deployed onchain: 786 B
Connecting to Stylus RPC endpoint: https://stylus-testnet.arbitrum.io/rpc
Program succeeded Stylus onchain activation checks with Stylus version: 1
Deploying program to address 0xc19ac697392eaaf3cca5505209542abf8edcd12e
Deploy / activation command failed: could not submit signed deployment tx: not estimate gas (code: -32000, message: gas required exceeds allowance (0), data: None)
```

**Comment by PlasmaPower** [comment]
Make sure the key you're using / the address it corresponds to has eth on the stylus testnet. Right now it seems to have 0. This is a different testnet than previously launched networks. To get eth, see the faucet and bridging instructions here: https://docs.arbitrum.io/stylus/stylus-quickstart#testnet-eth--sepolia

**Comment by rauljordan** [comment]
Hi @zklim do you have testnet eth in your account?

**Comment by zklim** [comment]
> Hi @zklim do you have testnet eth in your account?

Yes I just bridged it following the docs before trying out.

**Comment by zklim** [comment]
it says `exceeds allowance`, do I need to allow something?

**Comment by zklim** [comment]
Ah I know why, it bridged to Sepolia not Stylus lol
